config/routes.rb
Rails.application.routes.draw do
  resources :dailylogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dailylog.rb
class Dailylog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dailylogs_controller.rb
class DailylogsController < ApplicationController
  before_action :set_dailylog, only: [:show, :edit, :update, :destroy]

  # GET /dailylogs
  # GET /dailylogs.json
  def index
    @dailylogs = Dailylog.all
  end

  # GET /dailylogs/1
  # GET /dailylogs/1.json
  def show
  end

  # GET /dailylogs/new
  def new
    @dailylog = Dailylog.new
  end

  # GET /dailylogs/1/edit
  def edit
  end

  # POST /dailylogs
  # POST /dailylogs.json
  def create
    @dailylog = Dailylog.new(dailylog_params)

    respond_to do |format|
      if @dailylog.save
        format.html { redirect_to @dailylog, notice: 'Dailylog was successfully created.' }
        format.json { render :show, status: :created, location: @dailylog }
      else
        format.html { render :new }
        format.json { render json: @dailylog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dailylogs/1
  # PATCH/PUT /dailylogs/1.json
  def update
    respond_to do |format|
      if @dailylog.update(dailylog_params)
        format.html { redirect_to @dailylog, notice: 'Dailylog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dailylog }
      else
        format.html { render :edit }
        format.json { render json: @dailylog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dailylogs/1
  # DELETE /dailylogs/1.json
  def destroy
    @dailylog.destroy
    respond_to do |format|
      format.html { redirect_to dailylogs_url, notice: 'Dailylog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dailylog
      @dailylog = Dailylog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dailylog_params
      params.require(:dailylog).permit(:description, :daily_quotes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dailylogs_helper.rb
module DailylogsHelper
end

app/views/dailylogs/_form.html.erb
<%= form_for(dailylog) do |f| %>
  <% if dailylog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dailylog.errors.count, "error") %> prohibited this dailylog from being saved:</h2>

      <ul>
      <% dailylog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :daily_quotes %>
    <%= f.text_field :daily_quotes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dailylogs/edit.html.erb
<h1>Editing Dailylog</h1>

<%= render 'form', dailylog: @dailylog %>

<%= link_to 'Show', @dailylog %> |
<%= link_to 'Back', dailylogs_path %>

app/views/dailylogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dailylogs</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Daily quotes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dailylogs.each do |dailylog| %>
      <tr>
        <td><%= dailylog.description %></td>
        <td><%= dailylog.daily_quotes %></td>
        <td><%= dailylog.created_at.strftime("%Y-%m-%d %H-%M-%S") %></td>
        <td><%= link_to 'Show', dailylog %></td>
        <td><%#= link_to 'Edit', edit_dailylog_path(dailylog) %></td>
        <td><%#= link_to 'Destroy', dailylog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dailylog', new_dailylog_path %>

app/views/dailylogs/new.html.erb
<h1>New Dailylog</h1>

<%= render 'form', dailylog: @dailylog %>

<%= link_to 'Back', dailylogs_path %>

app/views/dailylogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @dailylog.description %>
</p>

<p>
  <strong>Daily quotes:</strong>
  <%= @dailylog.daily_quotes %>
</p>

<%= link_to 'Edit', edit_dailylog_path(@dailylog) %> |
<%= link_to 'Back', dailylogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningLog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>